---
spring:
  profiles: dev
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:example-app;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /console

---
server:
  port: 8081
